import { LegalPage } from "@/components/LegalPage";

export default function SafetyPage() {
  return (
    <LegalPage eyebrow="Safety" title="Know what Solum can—and cannot—do.">
      <section><h2>Solum is an AI</h2><p>Every companion is generated by software, even when the conversation sounds natural. It does not have human feelings, professional judgment, or independent awareness.</p></section>
      <section><h2>Not for emergencies</h2><p>Do not rely on Solum during a crisis or when someone may be in immediate danger. Contact local emergency services. In the United States and its territories, call or text 988 for the Suicide &amp; Crisis Lifeline.</p></section>
      <section><h2>Health and high-stakes decisions</h2><p>Do not treat companion responses as diagnosis, treatment, legal, financial, or other professional advice. Confirm important decisions with a qualified person who understands your situation.</p></section>
      <section><h2>Protect your privacy</h2><p>Avoid sharing passwords, payment-card numbers, government identifiers, exact financial details, or information about another person that you are not authorized to disclose.</p></section>
      <section><h2>Take a break when needed</h2><p>If a conversation increases distress, end the call and contact someone you trust. You can review and remove saved memories from Settings.</p></section>
    </LegalPage>
  );
}
